-- 1. Cấu hình hệ thống (sys_config)
create table sys_config
(
    id           bigserial
        primary key,
    config_key   varchar(100) not null
        unique,
    config_value text         not null,
    config_name  varchar(255),
    description  text,
    is_active    boolean   default true,
    created_at   timestamp default CURRENT_TIMESTAMP,
    updated_at   timestamp default CURRENT_TIMESTAMP
);

alter table sys_config
    owner to postgres;

create index idx_config_key
    on sys_config (config_key);

-------------------------------------------------------------------------------------------------------------------
-- 2. User table (users)
create table users
(
    id         bigint generated by default as identity
        primary key,
    email      varchar(255),
    full_name  varchar(255),
    password   varchar(255),
    role       varchar(255)
        constraint users_role_check
            check ((role)::text = ANY
        ((ARRAY ['ADMIN'::character varying, 'PROJECT_MANAGER'::character varying, 'EDITOR'::character varying])::text[])),
    status     varchar(255)
        constraint users_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])),
    username   varchar(255),
    created_at timestamp(6),
    created_by varchar(255),
    updated_at timestamp(6),
    updated_by varchar(255)
);

alter table users
    owner to postgres;

----------------------------------------------------------------------------------------------------